#!/bin/bash

if [ $# -eq 0 ]
then
	echo "Usage: phone searchfor[...searchfor]"
	echo "(You didn't tell me what you want to search for.)"
	exit
fi

search=$1

for i in $*
do
	
		search=$search'|'$i
done


egrep -i "$search" data | awk -f display.awk
